name: Build and Deploy LegalCheck Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  VERSION: ${{ github.event.inputs.environment || 'production' }}-${{ github.sha }}

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Generate unique cache key
        id: cache-key
        run: echo "key=frontend-${{ github.sha }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Checkout frontend repository
        uses: actions/checkout@v4
        with:
          path: 'frontend'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Create frontend .env file
        run: |
          echo "APP_ENV=${{ github.event.inputs.environment || 'production' }}" > frontend/.env

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npx expo export --clear

      - name: Cache frontend build
        uses: actions/cache@v4
        with:
          path: frontend/dist
          key: ${{ steps.cache-key.outputs.key }}

  build-backend:
    name: Build Nginx
    runs-on: ubuntu-latest
    needs: build-frontend
    outputs:
      nginx-image: ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:${{ env.VERSION }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          repository: hrsa/LegalCheck
          path: 'backend'
          token: ${{ secrets.GH_BACKEND_PAT }}

      - name: Restore frontend build
        uses: actions/cache@v4
        with:
          path: frontend/dist
          key: ${{ needs.build-frontend.outputs.cache-key }}

      - name: Copy dist folder to backend
        run: |
          mkdir -p backend/dist
          cp -r frontend/dist/* backend/dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and cache Nginx images
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/docker/nginx.dockerfile
          target: prod
          push: false
          load: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:${{ env.VERSION }}
          build-args: |
            UID=1001
            GID=1001
            USER=anton
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:buildcache,mode=max

      - name: Push Docker images to registry
        run: |
          docker tag ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:${{ env.VERSION }} ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:latest

          docker push ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:${{ env.VERSION }}
          docker push ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:latest

      - name: Clean up
        working-directory: backend
        run: docker compose -f docker-compose-prod.yml down

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-backend
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:

      - name: Create an SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ env.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            cd /var/www
            if [ -f docker-compose.yml ]; then
              cp docker-compose.yml docker-compose.yml.backup
            fi
            
            sed -i -E 's|image: ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:[a-zA-Z0-9_-]+|image: ${{ env.DOCKER_HUB_USERNAME }}/legalcheck-nginx:${{ env.VERSION }}|g' docker-compose.yml
            
            docker compose down
            docker image prune -a -f --filter "reference=hrsa/legalcheck-nginx:*"
            docker compose pull nginx
            docker compose up -d nginx
            
            echo "Waiting for application to be healthy..."
            timeout=120
            until curl -s -f http://localhost  > /dev/null || [ $timeout -le 0 ]
            do
              sleep 2
              ((timeout-=2))
              echo "Waiting for application... $timeout seconds left"
            done
            
            if [ $timeout -le 0 ]; then
              echo "Application failed to start in time, rolling back..."
              docker compose down
              mv docker-compose.yml.backup docker-compose.yml
              docker compose up -d nginx
              exit 1
            else
              echo "Application is healthy!"
            fi